# -*- coding: utf-8 -*-
"""valor_mensal_de_importacao_de_cafe_no_brasil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9CgXyS7F0-8LHYIRR1KJQFBHNXA7OWR
"""

# Nome: Daniel da Costa Lima  RA: 2021.1.08.026

# Departamento de Agricultura dos Estados Unidos
# https://www.kaggle.com/datasets/srishti1209/coffee-imports-in-brazil

"""Bibliotecas necessárias"""

# Análise e manipulação de dados
import pandas as pd

# Manipulação de vetores e matrizes
import numpy as np  

# Geração de gráficos
import plotly
import plotly.offline as py

# Carregar dados CSV
from pandas import read_csv

from google.colab import drive
drive.mount('/content/drive')

# Leitura do banco de dados
filename='/content/drive/MyDrive/Inteligência Artificial/Banco de dados/Coffee_Time Series.csv'
series = pd.read_csv(filename)

# Exibindo os 5 primeiros e 5 últimos elementos da série
series

# Analisando as informações gerais do Data Frame
series.info()

"""Gráfico da quantidade de importações de café no Brasil de janeiro de 1990 a junho de 2022"""

# Gerando o gráfico
import plotly.graph_objs as go 

data = [ go.Scatter(
          x=series['Month Year'],
          y=series['Value of Import'],
          line = dict(color = '#17BECF'),
          opacity = 0.8)]

py.iplot(data)

"""Associando "Month Year"e "Value of Import"
"""

# Variável "importacoes" - contém todos os meses/anos e todos os valores de importações de café no Brasil
importacoes = series.loc[:,["Month Year","Value of Import"]] #seleciona as 2 colunas
importacoes

"""Checando a existência de valores duplicados e/ou nulos"""

# Verificação da existência valores duplicados
importacoes.drop_duplicates(inplace=True)

# Verificação da existência valores nulos
importacoes.dropna(inplace=True)

"""Criando a matriz de conhecimento

"""

# Definindo o tamanho da janela deslizante 
janela = 12

# Quantidade de linhas
lin = len(importacoes)    #-janela

# Criando uma matriz de zeros
matriz = np.zeros(((lin - janela), janela+1))
print(matriz)

# Armazenando os valores de importações em um vetor numpy (facilita a indexação)
valores = importacoes["Value of Import"].to_numpy()

# Preenchendo a matriz com os valores do banco de dados
for i in range(lin - janela):
    for j in range(janela + 1):
        matriz[i][j] = valores[i+j]

# Exibindo os elementos da matriz
print(matriz)

# Criando o data frame tabela, atribuindo índices às linhas e colunas
tabela = pd.DataFrame(matriz)
tabela.columns = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', 'Saída']
i = 1
tabela.index = range(1, i + len(tabela))
tabela